name: Android CI

on:
  pull_request:

jobs:
  ci_test:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Cache Gradle packages
        uses: actions/cache@v3.0.11
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/buildSrc/**/*.kt') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
            
      - name: Access Client_ID
        run: |
          echo API_CLIENT_ID=\"$API_KEY\" > local.properties
        shell: bash
        env:
          API_KEY: ${{ secrets.API_CLIENT_ID }}
          
      - name: Access Client_Secret
        run: |
          echo API_CLIENT_SECRET=\"$API_KEY\" > local.properties
        shell: bash
        env:
          API_KEY: ${{ secrets.API_CLIENT_SECRET }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Gradle test
        run: ./gradlew test

      - name: Create android test report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }} 

  ci_build:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Cache Gradle packages
        uses: actions/cache@v3.0.11
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/buildSrc/**/*.kt') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
            
      - name: Access Client_ID
        run: |
          echo API_CLIENT_ID=\"$API_KEY\" > local.properties
        shell: bash
        env:
          API_KEY: ${{ secrets.API_CLIENT_ID }}
          
      - name: Access Client_Secret
        run: |
          echo API_CLIENT_SECRET=\"$API_KEY\" > local.properties
        shell: bash
        env:
          API_KEY: ${{ secrets.API_CLIENT_SECRET }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Gradle Build without test
        run: ./gradlew build -x test
        
        
